// <auto-generated />
using System;
using Kaszinó_projekt;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kaszinó_projekt.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20260505101253_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Kaszinó_projekt.Modells.Adatokmodell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Admin")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Egyenleg")
                        .HasColumnType("int");

                    b.Property<int>("Eletkor")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Jelszo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FelhasználóAdatok");
                });

            modelBuilder.Entity("Kaszinó_projekt.Modells.JátékokAdatai", b =>
                {
                    b.Property<int>("JátékId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EgyenlegJatekElott")
                        .HasColumnType("int");

                    b.Property<int>("EgyenlegJatekUtan")
                        .HasColumnType("int");

                    b.Property<int>("FelhasznaloId")
                        .HasColumnType("int");

                    b.Property<string>("JatekTipus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Nyeremeny")
                        .HasColumnType("int");

                    b.Property<int?>("Nyerovonalak")
                        .HasColumnType("int");

                    b.Property<int>("Tet")
                        .HasColumnType("int");

                    b.HasKey("JátékId");

                    b.HasIndex("FelhasznaloId");

                    b.ToTable("JátékokAdatai", (string)null);
                });

            modelBuilder.Entity("Kaszinó_projekt.Modells.Kaszinobevitel", b =>
                {
                    b.Property<int>("TranzakcióId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Bevitel")
                        .HasColumnType("int");

                    b.Property<DateTime>("Dátum")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FelhasználóId")
                        .HasColumnType("int");

                    b.Property<int>("Kiadás")
                        .HasColumnType("int");

                    b.HasKey("TranzakcióId");

                    b.ToTable("KaszinóBevitel");
                });

            modelBuilder.Entity("Kaszinó_projekt.Modells.JátékokAdatai", b =>
                {
                    b.HasOne("Kaszinó_projekt.Modells.Adatokmodell", "Felhasznalo")
                        .WithMany()
                        .HasForeignKey("FelhasznaloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Felhasznalo");
                });
#pragma warning restore 612, 618
        }
    }
}
